M48
; DRILL file {KiCad 7.0.7} date Sun Dec 10 19:04:38 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-10T19:04:38-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X6.5815Y-6.0327
X6.8091Y-6.0327
T2
X8.4279Y-5.2091
X8.4279Y-5.3272
T3
X5.002Y-5.1504
X5.002Y-5.4654
T0
M30
