M48
; DRILL file {KiCad 7.0.1} date Thu Dec 14 09:52:13 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-14T09:52:13-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X167.17Y-153.23
X172.95Y-153.23
T2
X214.069Y-132.311
X214.069Y-135.311
T3
X127.05Y-130.82
X127.05Y-138.82
T0
M30
