version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BMS_API_URL=http://localhost:4200
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # This will allow the container to access the host's hardware
    privileged: true
